#!/bin/make

# build directory
BUILDPATH = ./build
LIBPATH = ./lib
LIBNAME = libpubsub.a

CXX = g++
INCLUDE = -I /usr/local/include -I /usr/include -I./include
CXXFLAGS = -Wall -O2 $(INCLUDE)
LDFLAGS = -L /usr/lib -L /usr/local/lib


BUILDPATH:

